#!/bin/bash
# FuelAnchor Smart Contract Deployment Script
# Deploys all Soroban contracts to Stellar Testnet

set -e  # Exit on error

echo "🚀 FuelAnchor Contract Deployment to Testnet"
echo "=============================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if stellar CLI is installed
if ! command -v stellar &> /dev/null; then
    echo -e "${RED}❌ Stellar CLI not found!${NC}"
    echo "Install it with: cargo install --locked stellar-cli"
    exit 1
fi

echo -e "${GREEN}✅ Stellar CLI found${NC}"
echo ""

# Configure network if not already configured
echo -e "${BLUE}📡 Configuring Stellar Testnet...${NC}"
stellar network add testnet \
  --rpc-url https://soroban-testnet.stellar.org:443 \
  --network-passphrase "Test SDF Network ; September 2015" 2>/dev/null || true

# Check if admin keypair exists, if not create it
if ! stellar keys address admin 2>/dev/null; then
    echo -e "${YELLOW}🔑 Generating admin keypair...${NC}"
    stellar keys generate admin --network testnet
    ADMIN_ADDRESS=$(stellar keys address admin)
    echo -e "${GREEN}✅ Admin address: $ADMIN_ADDRESS${NC}"
    echo ""
    echo -e "${YELLOW}⚠️  IMPORTANT: Fund this account at:${NC}"
    echo -e "${BLUE}https://laboratory.stellar.org/#account-creator?network=test${NC}"
    echo ""
    echo "Press Enter after funding the account..."
    read
else
    ADMIN_ADDRESS=$(stellar keys address admin)
    echo -e "${GREEN}✅ Using existing admin: $ADMIN_ADDRESS${NC}"
fi

echo ""
echo -e "${BLUE}🔨 Building all contracts...${NC}"
cd contracts

# Build all contracts
echo "Building fuel-token..."
cd fuel-token
stellar contract build
cd ..

echo "Building fuel-lock..."
cd fuel-lock
stellar contract build
cd ..

echo "Building voucher-redemption..."
cd voucher-redemption
stellar contract build
cd ..

echo "Building credit-score..."
cd credit-score
stellar contract build
cd ..

echo "Building geofencing..."
cd geofencing
stellar contract build
cd ..

echo -e "${GREEN}✅ All contracts built successfully${NC}"
echo ""

# Create .env file for backend
ENV_FILE="../backend/.env"
echo -e "${BLUE}📝 Creating backend .env file...${NC}"
cat > $ENV_FILE << 'EOF'
# FuelAnchor Backend Environment Configuration
# Generated by deploy_contracts.sh

# Server Configuration
PORT=3000
NODE_ENV=development

# Stellar Network Configuration
STELLAR_NETWORK=testnet
STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
STELLAR_SOROBAN_RPC_URL=https://soroban-testnet.stellar.org:443
STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2015

# Admin Keypair (DO NOT COMMIT TO GIT - Add to .gitignore)
STELLAR_ADMIN_SECRET=YOUR_ADMIN_SECRET_HERE

# CORS Origins
CORS_ORIGINS=http://localhost:3000,http://localhost:8080

# Database (Supabase)
DATABASE_URL=

EOF

echo ""
echo -e "${BLUE}🚀 Deploying contracts to testnet...${NC}"
echo ""

# Deploy fuel-token
echo -e "${YELLOW}Deploying fuel-token...${NC}"
cd fuel-token
FUEL_TOKEN_ID=$(stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/fuel_token.wasm \
  --source admin \
  --network testnet)
echo -e "${GREEN}✅ Fuel Token deployed: $FUEL_TOKEN_ID${NC}"
echo "FUEL_TOKEN_CONTRACT_ID=$FUEL_TOKEN_ID" >> $ENV_FILE
cd ..

# Deploy fuel-lock
echo -e "${YELLOW}Deploying fuel-lock...${NC}"
cd fuel-lock
FUEL_LOCK_ID=$(stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/fuel_lock.wasm \
  --source admin \
  --network testnet)
echo -e "${GREEN}✅ Fuel Lock deployed: $FUEL_LOCK_ID${NC}"
echo "FUEL_LOCK_CONTRACT_ID=$FUEL_LOCK_ID" >> $ENV_FILE
cd ..

# Deploy voucher-redemption
echo -e "${YELLOW}Deploying voucher-redemption...${NC}"
cd voucher-redemption
VOUCHER_ID=$(stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/voucher_redemption.wasm \
  --source admin \
  --network testnet)
echo -e "${GREEN}✅ Voucher Redemption deployed: $VOUCHER_ID${NC}"
echo "VOUCHER_REDEMPTION_CONTRACT_ID=$VOUCHER_ID" >> $ENV_FILE
cd ..

# Deploy credit-score
echo -e "${YELLOW}Deploying credit-score...${NC}"
cd credit-score
CREDIT_SCORE_ID=$(stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/credit_score.wasm \
  --source admin \
  --network testnet)
echo -e "${GREEN}✅ Credit Score deployed: $CREDIT_SCORE_ID${NC}"
echo "CREDIT_SCORE_CONTRACT_ID=$CREDIT_SCORE_ID" >> $ENV_FILE
cd ..

# Deploy geofencing
echo -e "${YELLOW}Deploying geofencing...${NC}"
cd geofencing
GEOFENCING_ID=$(stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/geofencing.wasm \
  --source admin \
  --network testnet)
echo -e "${GREEN}✅ Geofencing deployed: $GEOFENCING_ID${NC}"
echo "GEOFENCING_CONTRACT_ID=$GEOFENCING_ID" >> $ENV_FILE
cd ..

cd ..

echo ""
echo -e "${GREEN}🎉 All contracts deployed successfully!${NC}"
echo ""
echo -e "${BLUE}📋 Deployment Summary:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "Fuel Token:          ${GREEN}$FUEL_TOKEN_ID${NC}"
echo -e "Fuel Lock:           ${GREEN}$FUEL_LOCK_ID${NC}"
echo -e "Voucher Redemption:  ${GREEN}$VOUCHER_ID${NC}"
echo -e "Credit Score:        ${GREEN}$CREDIT_SCORE_ID${NC}"
echo -e "Geofencing:          ${GREEN}$GEOFENCING_ID${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${YELLOW}📝 Next Steps:${NC}"
echo "1. Add your admin secret key to backend/.env (STELLAR_ADMIN_SECRET)"
echo "2. Update Flutter app with contract IDs (see CONTRACT_IDS.txt)"
echo "3. Run 'npm run dev' in backend folder"
echo "4. Test the integration!"
echo ""

# Save contract IDs to a text file for Flutter integration
cat > CONTRACT_IDS.txt << EOF
FuelAnchor Contract IDs - Stellar Testnet
Generated: $(date)

Update these in your Flutter app:
frontend_flutter/lib/features/blockchain/data/services/stellar_service.dart

FUEL_TOKEN_CONTRACT_ID=$FUEL_TOKEN_ID
FUEL_LOCK_CONTRACT_ID=$FUEL_LOCK_ID
VOUCHER_REDEMPTION_CONTRACT_ID=$VOUCHER_ID
CREDIT_SCORE_CONTRACT_ID=$CREDIT_SCORE_ID
GEOFENCING_CONTRACT_ID=$GEOFENCING_ID

Admin Address: $ADMIN_ADDRESS
Network: Stellar Testnet
RPC URL: https://soroban-testnet.stellar.org:443
EOF

echo -e "${GREEN}✅ Contract IDs saved to CONTRACT_IDS.txt${NC}"
