# FuelAnchor Smart Contract Deployment Script (PowerShell)
# Deploys all Soroban contracts to Stellar Testnet

$ErrorActionPreference = "Stop"

Write-Host "🚀 FuelAnchor Contract Deployment to Testnet" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host ""

# Check if stellar CLI is installed
$stellarCmd = Get-Command stellar -ErrorAction SilentlyContinue
if (-not $stellarCmd) {
    Write-Host "❌ Stellar CLI not found!" -ForegroundColor Red
    Write-Host "Install it with: cargo install --locked stellar-cli" -ForegroundColor Yellow
    exit 1
}

Write-Host "✅ Stellar CLI found" -ForegroundColor Green
Write-Host ""

# Configure network
Write-Host "📡 Configuring Stellar Testnet..." -ForegroundColor Blue
stellar network add testnet `
  --rpc-url https://soroban-testnet.stellar.org:443 `
  --network-passphrase "Test SDF Network ; September 2015" 2>$null

# Check if admin keypair exists
$adminExists = $false
try {
    $adminAddress = stellar keys address admin 2>&1
    if ($LASTEXITCODE -eq 0) {
        $adminExists = $true
    }
} catch {}

if (-not $adminExists) {
    Write-Host "🔑 Generating admin keypair..." -ForegroundColor Yellow
    stellar keys generate admin --network testnet
    $adminAddress = stellar keys address admin
    Write-Host "✅ Admin address: $adminAddress" -ForegroundColor Green
    Write-Host ""
    Write-Host "⚠️  IMPORTANT: Fund this account at:" -ForegroundColor Yellow
    Write-Host "https://laboratory.stellar.org/#account-creator?network=test" -ForegroundColor Blue
    Write-Host ""
    Write-Host "Press Enter after funding the account..." -ForegroundColor Yellow
    Read-Host
} else {
    $adminAddress = stellar keys address admin
    Write-Host "✅ Using existing admin: $adminAddress" -ForegroundColor Green
}

Write-Host ""
Write-Host "🔨 Building all contracts..." -ForegroundColor Blue
Set-Location contracts

# Build all contracts
Write-Host "Building fuel-token..." -ForegroundColor Cyan
Set-Location fuel-token
stellar contract build
Set-Location ..

Write-Host "Building fuel-lock..." -ForegroundColor Cyan
Set-Location fuel-lock
stellar contract build
Set-Location ..

Write-Host "Building voucher-redemption..." -ForegroundColor Cyan
Set-Location voucher-redemption
stellar contract build
Set-Location ..

Write-Host "Building credit-score..." -ForegroundColor Cyan
Set-Location credit-score
stellar contract build
Set-Location ..

Write-Host "Building geofencing..." -ForegroundColor Cyan
Set-Location geofencing
stellar contract build
Set-Location ..

Write-Host "✅ All contracts built successfully" -ForegroundColor Green
Write-Host ""

# Create .env file for backend
$envFile = "..\backend\.env"
Write-Host "📝 Creating backend .env file..." -ForegroundColor Blue

@"
# FuelAnchor Backend Environment Configuration
# Generated by deploy_contracts.ps1

# Server Configuration
PORT=3000
NODE_ENV=development

# Stellar Network Configuration
STELLAR_NETWORK=testnet
STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
STELLAR_SOROBAN_RPC_URL=https://soroban-testnet.stellar.org:443
STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2015

# Admin Keypair (DO NOT COMMIT TO GIT - Add to .gitignore)
STELLAR_ADMIN_SECRET=YOUR_ADMIN_SECRET_HERE

# CORS Origins
CORS_ORIGINS=http://localhost:3000,http://localhost:8080

# Database (Supabase)
DATABASE_URL=

"@ | Out-File -FilePath $envFile -Encoding UTF8

Write-Host ""
Write-Host "🚀 Deploying contracts to testnet..." -ForegroundColor Blue
Write-Host ""

# Deploy fuel-token
Write-Host "Deploying fuel-token..." -ForegroundColor Yellow
Set-Location fuel-token
$FUEL_TOKEN_ID = stellar contract deploy `
  --wasm target/wasm32-unknown-unknown/release/fuel_token.wasm `
  --source admin `
  --network testnet
Write-Host "✅ Fuel Token deployed: $FUEL_TOKEN_ID" -ForegroundColor Green
Add-Content -Path $envFile -Value "FUEL_TOKEN_CONTRACT_ID=$FUEL_TOKEN_ID"
Set-Location ..

# Deploy fuel-lock
Write-Host "Deploying fuel-lock..." -ForegroundColor Yellow
Set-Location fuel-lock
$FUEL_LOCK_ID = stellar contract deploy `
  --wasm target/wasm32-unknown-unknown/release/fuel_lock.wasm `
  --source admin `
  --network testnet
Write-Host "✅ Fuel Lock deployed: $FUEL_LOCK_ID" -ForegroundColor Green
Add-Content -Path $envFile -Value "FUEL_LOCK_CONTRACT_ID=$FUEL_LOCK_ID"
Set-Location ..

# Deploy voucher-redemption
Write-Host "Deploying voucher-redemption..." -ForegroundColor Yellow
Set-Location voucher-redemption
$VOUCHER_ID = stellar contract deploy `
  --wasm target/wasm32-unknown-unknown/release/voucher_redemption.wasm `
  --source admin `
  --network testnet
Write-Host "✅ Voucher Redemption deployed: $VOUCHER_ID" -ForegroundColor Green
Add-Content -Path $envFile -Value "VOUCHER_REDEMPTION_CONTRACT_ID=$VOUCHER_ID"
Set-Location ..

# Deploy credit-score
Write-Host "Deploying credit-score..." -ForegroundColor Yellow
Set-Location credit-score
$CREDIT_SCORE_ID = stellar contract deploy `
  --wasm target/wasm32-unknown-unknown/release/credit_score.wasm `
  --source admin `
  --network testnet
Write-Host "✅ Credit Score deployed: $CREDIT_SCORE_ID" -ForegroundColor Green
Add-Content -Path $envFile -Value "CREDIT_SCORE_CONTRACT_ID=$CREDIT_SCORE_ID"
Set-Location ..

# Deploy geofencing
Write-Host "Deploying geofencing..." -ForegroundColor Yellow
Set-Location geofencing
$GEOFENCING_ID = stellar contract deploy `
  --wasm target/wasm32-unknown-unknown/release/geofencing.wasm `
  --source admin `
  --network testnet
Write-Host "✅ Geofencing deployed: $GEOFENCING_ID" -ForegroundColor Green
Add-Content -Path $envFile -Value "GEOFENCING_CONTRACT_ID=$GEOFENCING_ID"
Set-Location ..

Set-Location ..

Write-Host ""
Write-Host "🎉 All contracts deployed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Deployment Summary:" -ForegroundColor Blue
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host "Fuel Token:          $FUEL_TOKEN_ID" -ForegroundColor Green
Write-Host "Fuel Lock:           $FUEL_LOCK_ID" -ForegroundColor Green
Write-Host "Voucher Redemption:  $VOUCHER_ID" -ForegroundColor Green
Write-Host "Credit Score:        $CREDIT_SCORE_ID" -ForegroundColor Green
Write-Host "Geofencing:          $GEOFENCING_ID" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host ""
Write-Host "📝 Next Steps:" -ForegroundColor Yellow
Write-Host "1. Add your admin secret key to backend/.env (STELLAR_ADMIN_SECRET)"
Write-Host "2. Update Flutter app with contract IDs (see CONTRACT_IDS.txt)"
Write-Host "3. Run 'npm run dev' in backend folder"
Write-Host "4. Test the integration!"
Write-Host ""

# Save contract IDs to a text file
$contractIdsFile = "CONTRACT_IDS.txt"
@"
FuelAnchor Contract IDs - Stellar Testnet
Generated: $(Get-Date)

Update these in your Flutter app:
frontend_flutter/lib/features/blockchain/data/services/stellar_service.dart

FUEL_TOKEN_CONTRACT_ID=$FUEL_TOKEN_ID
FUEL_LOCK_CONTRACT_ID=$FUEL_LOCK_ID
VOUCHER_REDEMPTION_CONTRACT_ID=$VOUCHER_ID
CREDIT_SCORE_CONTRACT_ID=$CREDIT_SCORE_ID
GEOFENCING_CONTRACT_ID=$GEOFENCING_ID

Admin Address: $adminAddress
Network: Stellar Testnet
RPC URL: https://soroban-testnet.stellar.org:443
"@ | Out-File -FilePath $contractIdsFile -Encoding UTF8

Write-Host "✅ Contract IDs saved to CONTRACT_IDS.txt" -ForegroundColor Green
