#!/bin/bash
# Contract ABI Auto-Generation Script (Unix/Linux/macOS)
# Extracts contract metadata and generates Dart bindings for Flutter

set -e

NETWORK="${1:-testnet}"
OUTPUT_DIR="${2:-../frontend_flutter/lib/features/blockchain/generated}"

echo "🔧 FuelAnchor Contract ABI Generator"
echo "====================================="
echo ""

# Check if Soroban CLI is installed
if ! command -v soroban &> /dev/null; then
    echo "❌ Soroban CLI not found. Install it with:"
    echo "   cargo install --locked soroban-cli"
    exit 1
fi

# Check if CONTRACT_IDS.txt exists
if [ ! -f "../CONTRACT_IDS.txt" ]; then
    echo "❌ CONTRACT_IDS.txt not found. Deploy contracts first."
    exit 1
fi

# Read contract IDs
echo "📖 Reading contract IDs..."
declare -A CONTRACT_IDS

while IFS='=' read -r key value; do
    if [[ $key =~ ^[A-Z_]+_CONTRACT_ID$ ]]; then
        clean_key="${key/_CONTRACT_ID/}"
        clean_value=$(echo "$value" | xargs)
        CONTRACT_IDS["$clean_key"]="$clean_value"
        echo "  ✓ $clean_key : $clean_value"
    fi
done < "../CONTRACT_IDS.txt"

# Create output directory
mkdir -p "$OUTPUT_DIR"
echo "📁 Output directory: $OUTPUT_DIR"
echo ""

echo "🔍 Extracting contract metadata..."
echo ""

# Function to convert Soroban type to Dart type
soroban_to_dart_type() {
    case "$1" in
        u32|u64|i32|i64) echo "int" ;;
        u128|i128) echo "BigInt" ;;
        bool) echo "bool" ;;
        symbol|string|address) echo "String" ;;
        bytes) echo "List<int>" ;;
        vec) echo "List" ;;
        map) echo "Map" ;;
        *) echo "dynamic" ;;
    esac
}

# Generate Dart binding for each contract
GENERATED_FILES=()

for contract_key in "${!CONTRACT_IDS[@]}"; do
    CONTRACT_ID="${CONTRACT_IDS[$contract_key]}"
    CONTRACT_NAME=$(echo "$contract_key" | tr '[:upper:]_' '[:lower:]-')
    CLASS_NAME="${CONTRACT_NAME//-/_}Contract"
    FILE_NAME="${CONTRACT_NAME}_contract.dart"
    FILE_PATH="${OUTPUT_DIR}/${FILE_NAME}"

    echo "  Processing $contract_key..."

    # Generate Dart file
    cat > "$FILE_PATH" << EOF
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: scripts/generate_contract_bindings.sh

import 'package:stellar_flutter_sdk/stellar_flutter_sdk.dart';

/// $contract_key Smart Contract Binding
/// Contract ID: $CONTRACT_ID
class ${CLASS_NAME} {
  static const String contractId = '$CONTRACT_ID';
  
  final SorobanServer server;
  final String networkPassphrase;

  ${CLASS_NAME}({
    required this.server,
    required this.networkPassphrase,
  });

  /// Helper method to build and submit contract invocation
  Future<String> _invokeContract({
    required Keypair sourceKeypair,
    required String functionName,
    required List<XdrSCVal> args,
  }) async {
    final sourceAccount = await server.getAccount(sourceKeypair.accountId);
    
    final invokeOperation = InvokeContractHostFunction(
      contractId,
      functionName,
      arguments: args,
    );

    final transaction = TransactionBuilder(sourceAccount)
        .addOperation(invokeOperation)
        .build();

    transaction.sign(sourceKeypair, Network(networkPassphrase));

    final response = await server.sendTransaction(transaction);
    return response.hash;
  }

  /// Invoke a contract method
  Future<String> invokeMethod(
    Keypair sourceKeypair,
    String functionName,
    List<XdrSCVal> args,
  ) async {
    return await _invokeContract(
      sourceKeypair: sourceKeypair,
      functionName: functionName,
      args: args,
    );
  }
}
EOF

    echo "    ✓ Generated $FILE_NAME"
    GENERATED_FILES+=("$FILE_NAME")
done

echo ""
echo "📝 Generating barrel export file..."

# Create barrel export file
BARREL_FILE="${OUTPUT_DIR}/contracts.dart"
cat > "$BARREL_FILE" << EOF
// GENERATED CODE - DO NOT MODIFY BY HAND
// Barrel file for all contract bindings

EOF

for file in "${GENERATED_FILES[@]}"; do
    echo "export '$file';" >> "$BARREL_FILE"
done

echo "  ✓ Generated contracts.dart"

echo ""
echo "✅ Contract bindings generated successfully!"
echo "   Output: $OUTPUT_DIR"
echo ""
echo "📝 Next steps:"
echo "   1. Review generated files in $OUTPUT_DIR"
echo "   2. Run 'flutter pub run build_runner build' to generate Riverpod providers"
echo "   3. Import contracts in your code: import 'package:fuelanchor/features/blockchain/generated/contracts.dart';"
echo ""
