#!/usr/bin/env pwsh
# Contract ABI Auto-Generation Script
# Extracts contract metadata and generates Dart bindings for Flutter

param(
    [string]$Network = "testnet",
    [string]$OutputDir = "../frontend_flutter/lib/features/blockchain/generated"
)

$ErrorActionPreference = "Stop"

Write-Host "🔧 FuelAnchor Contract ABI Generator" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host ""

# Check if Soroban CLI is installed
if (-not (Get-Command soroban -ErrorAction SilentlyContinue)) {
    Write-Host "❌ Soroban CLI not found. Install it with:" -ForegroundColor Red
    Write-Host "   cargo install --locked soroban-cli" -ForegroundColor Yellow
    exit 1
}

# Check if CONTRACT_IDS.txt exists
if (-not (Test-Path "../CONTRACT_IDS.txt")) {
    Write-Host "❌ CONTRACT_IDS.txt not found. Deploy contracts first." -ForegroundColor Red
    exit 1
}

# Read contract IDs
Write-Host "📖 Reading contract IDs..." -ForegroundColor Yellow
$contractIds = @{}
Get-Content "../CONTRACT_IDS.txt" | Where-Object { $_ -match "^[A-Z_]+_CONTRACT_ID=" } | ForEach-Object {
    $parts = $_ -split "=", 2
    $key = $parts[0] -replace "_CONTRACT_ID", ""
    $value = $parts[1].Trim()
    $contractIds[$key] = $value
    Write-Host "  ✓ $key : $value" -ForegroundColor Green
}

# Create output directory
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
    Write-Host "📁 Created output directory: $OutputDir" -ForegroundColor Green
}

Write-Host ""
Write-Host "🔍 Extracting contract metadata..." -ForegroundColor Yellow
Write-Host ""

# Function to extract contract spec
function Get-ContractSpec {
    param(
        [string]$ContractId,
        [string]$ContractName
    )

    Write-Host "  Processing $ContractName..." -ForegroundColor Cyan

    try {
        # Fetch contract spec using Soroban CLI
        $specJson = soroban contract bindings json `
            --network $Network `
            --contract-id $ContractId `
            2>&1

        if ($LASTEXITCODE -ne 0) {
            Write-Host "    ⚠ Failed to fetch spec for $ContractName" -ForegroundColor Yellow
            return $null
        }

        # Parse the JSON
        $spec = $specJson | ConvertFrom-Json

        Write-Host "    ✓ Extracted spec for $ContractName" -ForegroundColor Green

        return $spec
    }
    catch {
        Write-Host "    ⚠ Error extracting spec: $_" -ForegroundColor Yellow
        return $null
    }
}

# Function to convert Soroban type to Dart type
function ConvertTo-DartType {
    param([string]$SorobanType)

    switch ($SorobanType) {
        "u32" { return "int" }
        "u64" { return "int" }
        "u128" { return "BigInt" }
        "i32" { return "int" }
        "i64" { return "int" }
        "i128" { return "BigInt" }
        "bool" { return "bool" }
        "symbol" { return "String" }
        "string" { return "String" }
        "bytes" { return "List<int>" }
        "address" { return "String" }
        "vec" { return "List" }
        "map" { return "Map" }
        default { return "dynamic" }
    }
}

# Function to generate Dart class for contract
function Generate-DartBinding {
    param(
        [string]$ContractName,
        [string]$ContractId,
        [object]$Spec
    )

    $className = "${ContractName}Contract"
    $fileName = "${ContractName}_contract.dart"
    $filePath = Join-Path $OutputDir $fileName

    $dartCode = @"
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: scripts/generate_contract_bindings.ps1

import 'package:stellar_flutter_sdk/stellar_flutter_sdk.dart';

/// $ContractName Smart Contract Binding
/// Contract ID: $ContractId
class $className {
  static const String contractId = '$ContractId';
  
  final SorobanServer server;
  final String networkPassphrase;

  $className({
    required this.server,
    required this.networkPassphrase,
  });

  /// Helper method to build and submit contract invocation
  Future<String> _invokeContract({
    required Keypair sourceKeypair,
    required String functionName,
    required List<XdrSCVal> args,
  }) async {
    final sourceAccount = await server.getAccount(sourceKeypair.accountId);
    
    final invokeOperation = InvokeContractHostFunction(
      contractId,
      functionName,
      arguments: args,
    );

    final transaction = TransactionBuilder(sourceAccount)
        .addOperation(invokeOperation)
        .build();

    transaction.sign(sourceKeypair, Network(networkPassphrase));

    final response = await server.sendTransaction(transaction);
    return response.hash;
  }

  // Contract Methods
"@

    # Generate methods from spec (if available)
    if ($Spec -and $Spec.functions) {
        foreach ($func in $Spec.functions) {
            $methodName = $func.name
            $docComment = if ($func.doc) { "  /// $($func.doc)" } else { "" }
            
            $dartCode += @"

$docComment
  Future<String> $methodName() async {
    // TODO: Implement $methodName invocation
    throw UnimplementedError('$methodName not yet implemented');
  }
"@
        }
    }
    else {
        # Generate placeholder methods
        $dartCode += @"

  /// Invoke a contract method
  Future<String> invokeMethod(
    Keypair sourceKeypair,
    String functionName,
    List<XdrSCVal> args,
  ) async {
    return await _invokeContract(
      sourceKeypair: sourceKeypair,
      functionName: functionName,
      args: args,
    );
  }
"@
    }

    $dartCode += @"
}
"@

    # Write to file
    Set-Content -Path $filePath -Value $dartCode -Encoding UTF8
    Write-Host "    ✓ Generated $fileName" -ForegroundColor Green

    return $fileName
}

# Generate bindings for each contract
$generatedFiles = @()

foreach ($contract in $contractIds.Keys) {
    $contractId = $contractIds[$contract]
    $contractName = $contract.ToLower() -replace "_", "-"
    
    # Extract spec (may fail for some contracts, that's okay)
    $spec = Get-ContractSpec -ContractId $contractId -ContractName $contract
    
    # Generate Dart binding
    $fileName = Generate-DartBinding -ContractName $contractName -ContractId $contractId -Spec $spec
    $generatedFiles += $fileName
}

Write-Host ""
Write-Host "📝 Generating barrel export file..." -ForegroundColor Yellow

# Create barrel export file
$barrelFile = Join-Path $OutputDir "contracts.dart"
$barrelContent = @"
// GENERATED CODE - DO NOT MODIFY BY HAND
// Barrel file for all contract bindings

"@

foreach ($file in $generatedFiles) {
    $barrelContent += "export '$file';`n"
}

Set-Content -Path $barrelFile -Value $barrelContent -Encoding UTF8
Write-Host "  ✓ Generated contracts.dart" -ForegroundColor Green

Write-Host ""
Write-Host "✅ Contract bindings generated successfully!" -ForegroundColor Green
Write-Host "   Output: $OutputDir" -ForegroundColor Cyan
Write-Host ""
Write-Host "📝 Next steps:" -ForegroundColor Yellow
Write-Host "   1. Review generated files in $OutputDir" -ForegroundColor White
Write-Host "   2. Run 'flutter pub run build_runner build' to generate Riverpod providers" -ForegroundColor White
Write-Host "   3. Import contracts in your code: import 'package:fuelanchor/features/blockchain/generated/contracts.dart';" -ForegroundColor White
Write-Host ""
